const NUMBER_OF_TRIANGLES = 600;
const NUMBER_OF_DECORATIONS = 20;
const TREE_HEIGHT = 3;
const TREE_WIDTH = 1.4;

export {
    NUMBER_OF_TRIANGLES,
    NUMBER_OF_DECORATIONS,
    TREE_HEIGHT,
    TREE_WIDTH
};
